config/routes.rb
Rails.application.routes.draw do
    
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :students

    
    
  root 'home#index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'students/index'
 # get 'students/new'
    
    
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  #get 'addnew', to: 'students#new', as: 'addnew'
  #get 'students', to: 'students#index', as: 'students'
  
end

app/models/student.rb
class Student < ActiveRecord::Base
  def self.all_years
    %w(2020 2021 2022 2023 2024)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
    
  helper_method :current_user
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
      
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to "/students", notice: "Logged in"
    else
      flash.now[:alert] = "Invalid entry, please try again"
      render "new"
    end
  end
    
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out"
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    
  def student_params
     params.require(:student).permit(:first, :last, :CWID, :DOB, :advisor, :year, :semester, :lastMeet, :notes)
  end
    
  def show
     id = params[:id]
     @student = Student.find(id)
  end

  def list
     @student = Student.all
  end

  def index
    sort = params[:sort] || session[:sort]
    case sort
    when 'first'
      ordering,@first_header = {:first => :asc}, 'bg-warning hilite'
    when 'last'
      ordering,@last_header = {:last => :asc}, 'bg-warning hilite'
    end
    @all_years = Student.all_years
    @selected_years = params[:years] || session[:years] || {}

    if @selected_years == {}
      @selected_years = Hash[@all_years.map {|year| [year, year]}]
    end

    if params[:sort] != session[:sort] or params[:years] != session[:years]
      session[:sort] = sort
      session[:years] = @selected_years
      redirect_to :sort => sort, :years => @selected_years and return
    end
    @students = Student.where(year: @selected_years.keys).order(ordering)
  end

  def edit
     @student = Student.find params[:id]
  end

  def update
    @student = Student.find params[:id]
    @student.update_attributes!(student_params)
    flash[:notice] = "#{@student.first} #{@student.last} was successfully updated."
    redirect_to student_path(@student)
  end  

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    flash[:notice] = "Student '#{@student.last}' deleted."
    redirect_to students_path
  end   
    
  def new
    # default: render 'addnew' template
  end
    
   def student_params_new
     params.permit(:first, :last, :CWID, :DOB, :advisor, :year, :semester, :lastMeet, :notes)
  end   
    
  def create
    @student = Student.create!(student_params_new)
    redirect_to students_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/student_helper.rb
module StudentHelper
    
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1 class="u-text u-text-default u-title u-block-0ba8-5" style="text-align: center;" contenteditable="true" data-block="79" data-block-type="Text" data-block-selected="true" data-editable-id="b027">Department of&nbsp; Cyber and Computer Sciences</h1><br/>
<h2 style="text-align: center;">Advisee Tracker</h2>

<p>
<% if current_user %>
  Logged in as <%= current_user.email %>.
  <%= link_to "Log Out", logout_path %>
<% else %>
  <%= link_to "Sign Up", signup_path %> or 
  <%= link_to "Log In", login_path %>
<% end %>
</p>
    
<% if current_user %>
<p>
<%= link_to 'Users List', users_path %>
</p>
<p>
<%= link_to 'Student List', students_path %>
</p>
<% else %>
    <p style="font-size: 1.5em; text-align: center;">Please log in to continue</p>
<% end %>

<p style="font-size: 1.5em; text-align: center;">&nbsp;</p>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %link(rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous")
    %title Advisee Tracker
    = stylesheet_link_tag 'application', 'media' => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

    %body
      %div.container
        %div.navbar.navbar-expand-lg.bg-primary.text-white
          %h1.title Advisee Tracker
        #main
          - if flash[:notice]
            %div.alert.alert-danger
              #notice.message= flash[:notice]
          - elsif flash[:warning]
            %div.alert.alert-danger
              #warning.message= flash[:warning]

          = yield

app/views/students/edit.html.haml
-# edit.html.haml using partial

%h2 Edit Existing Student

= form_tag student_path(@student), :method => :put do

  = label :student, :first, 'First'
  = text_field :student, 'first'
  %br
  
  = label :student, :last, 'Last'
  = text_field :student, 'last'
  %br
  
  = label :student, :CWID, 'CWID'
  = text_field :student, 'CWID'
  %br
  
  = label :student, :advisor, 'Advisor'
  = text_field :student, 'advisor'
  %br

  = label :student, :year, 'Year'
  = select :student, :year, ['2020', '2021', '2022', '2023', '2024', '2025']

  = label :student, :semester, 'Semester'
  = select :student, :semester, ['Spring', 'Summer', 'Fall']
  %br
  
  = label :student, :lastMeet, 'Last Advised Date'
  = date_select :student, 'lastMeet'
  %br

  = label :student, :notes, 'Notes'
  %br
  = text_area :student, 'notes'
  %br

  = submit_tag 'Update Student Info', :class => 'btn btn-primary'

app/views/students/index.html.haml
-#  This file is app/views/list.html.haml
%h1 Students List

= form_tag students_path, :method => :get, :id => 'student' do
  = hidden_field_tag "first_name_sort", true if @first_header
  = hidden_field_tag "last_name_sort", true if @last_header
  = hidden_field_tag "advisor_sort", true if @advisor_header
  = hidden_field_tag "date_sort", true if @date_header
  Graduation Year:
  - @all_years.each do |year|
    = year
    = check_box_tag "years[#{year}]", 1, @selected_years.include?(year), :id => "years_#{year}"
  = submit_tag 'Refresh', :id => 'years_submit', :class => 'btn btn-primary'

%table#students.table.table-striped.col-md-12
  %thead
    %tr
      %th{:class => @first_header}= link_to 'First', students_path(:sort => 'first', :ratings => @selected_years), :id => 'first_header'
      %th{:class => @last_header}= link_to 'Last', students_path(:sort => 'last', :ratings => @selected_years), :id => 'last_header'
      %th CWID
      %th{:class => @advisor_header}= link_to 'Advisor', students_path(:sort => 'advisor', :ratings => @selected_years), :id => 'advisor_header'
      %th Graduation Year
      %th Graduation Semester
      %th{:class => @lastMeet_header}= link_to 'Date Last Advised', students_path(:sort => 'lastMeet', :ratings => @selected_years), :id => 'lastMeet_header'
      %th More Info
  %tbody
    - @students.each do |student|
      %tr
        %td= student.first
        %td= student.last
        %td= student.CWID
        %td= student.advisor
        %td= student.year
        %td= student.semester
        %td= student.lastMeet
        %td= link_to "More about #{student.last}", student_path(student)

= link_to 'Add New Student', new_student_path
%br
= link_to 'Go Back', root_path

app/views/students/new.html.erb
<p id="alert"><%= alert %></p>
<h1>Add New Student</h1>
<%= form_tag students_path do |form| %>
  <div class="field">
    <%= label_tag :First_Name %>
    <%= text_field_tag :first %>
  </div>
  <div class="field">
    <%= label_tag :Last_Name %>
    <%= text_field_tag :last %>
  </div>
<div class="field">
    <%= label_tag :CWID %>
    <%= text_field_tag :CWID %>
  </div>
<div class="field">
    <%= label_tag :DOB %>
    <%= date_field_tag :DOB %> 
</div>
<div class="field">
    <%= label_tag :advisor %>
    <%= text_field_tag :advisor %>
  </div>
<div class="field">
    <%= label_tag :Graduation_Year%>
    <%= text_field_tag :year %>
  </div>
<div class="field">
    <%= label_tag :Graduation_Semester%>
    <%= text_field_tag :semester %>
  </div>
<div class="field">
    <%= label_tag :Last_Advising%>
    <%= date_field_tag :lastMeet %>
  </div>
<div class="field">
    <%= label_tag :Meeting_Notes%>
    <%= text_field_tag :notes %>
  </div>

  <div class="actions">
    <%= submit_tag "Add Student", :class => 'btn btn-primary'%>
  </div>
<% end %>

app/views/students/show.html.haml
%h2 Student View

%table#students.table.table-striped.col-md-12
  %thead
    %tr
      %th Last Name
      %th First Name
      %th Graduation Year
      %th Graduation Semester
      %th CWID
      %th Academid Advisor
      %th Last Meeting
  %tbody
    %tr
      %td= @student.last
      %td= @student.first
      %td= @student.year
      %td= @student.semester
      %td= @student.CWID
      %td= @student.advisor
      %td= @student.lastMeet
      
    
      = button_to 'Delete', student_path(@student), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-primary'
      = link_to 'Back to student list', students_path, :class => 'btn btn-primary'
      = link_to 'Edit', edit_student_path(@student), :class => 'btn btn-primary'

%br
%h2 Meeting Notes
%table#students.table.table-striped.col-md-12
  %thead
    %tbody
      %tr
        %td= @student.notes
-#= link_to 'Add New Meeting', new_meeting_path
-# Add a table for the students meetings below

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>
<%= link_to 'Go Back', root_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', root_path %>